{
  Object failing=new Object(){
    @InjectMocks ThrowingConstructor failingConstructor;
  }
;
  try {
    MockitoAnnotations.initMocks(failing);
    fail();
  }
 catch (  MockitoException e) {
    Assertions.assertThat(e.getMessage()).contains("failingConstructor").contains("constructor").contains("threw an exception");
    Assertions.assertThat(e.getCause()).isInstanceOf(RuntimeException.class);
  }
}
