{
  Error error=new Error();
  stub(mock.add("quake")).andThrows(error);
  try {
    mock.add("quake");
    fail();
  }
 catch (  Error e) {
    assertEquals(error,e);
  }
}
