{
  IllegalArgumentException expected=new IllegalArgumentException("thrown by mock");
  doThrow(expected).when(mock).clear();
  try {
    mock.clear();
    fail();
  }
 catch (  Exception e) {
    assertEquals(expected,e);
  }
}
