{
  IllegalArgumentException expected=new IllegalArgumentException("thrown by mock");
  stubVoid(mock).toThrow(expected).on().clear();
  try {
    mock.clear();
    fail();
  }
 catch (  Exception e) {
    assertEquals(expected,e);
  }
}
