{
  when(mock.get(1)).thenThrow(new ExceptionOne());
  try {
    when(mock.get(1)).thenThrow(new ExceptionTwo());
    fail();
  }
 catch (  ExceptionOne e) {
  }
}
